version: "3.9"

services:
  db:
    image: postgres:16
    container_name: deaubit-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shortDB
      POSTGRES_USER: deaubit
      POSTGRES_PASSWORD: ZS73TP97P3g9
    ports:
      - "5432:5432"
    volumes:
      - deaubit-db-data:/var/lib/postgresql/data

volumes:
  deaubit-db-data:
